create database roy;
use roy;
create table company(ID int,NAME varchar(30),CGPA decimal(3,2));
describe company;
select NAME,ID,CGPA from company;
insert into company values(01,"naren",8.00);
insert into company values(02,"nithin",8.05);
insert into company values(03,"teja",8.08);
select NAME,ID,CGPA from company where CGPA>=8.05;
select NAME,ID,CGPA from company where CGPA<9.00;
select NAME,ID,CGPA from company where CGPA<8.00;

create table employee1(ID int primary key,NAME varchar(30),salary int,DESIGNATION varchar(40));
insert into employee1 values(01,"naren",100000,"MANAGER");
insert into employee1 values(02,"nithin",90000,"TEAM LEAD");
insert into employee1 values(03,"teja",80000,"HR");
insert into employee1 values(04,"pavan",70000,"SENIOR");
insert into employee1 values(05,"sai",60000,"FRESHER");
 select * from employee1;
 select * from employee1 where ename ='sai';
 describe employee;
 describe employee1;
 select * from employee;
 select * from employee1;
 select * from employee1 where salary>110000 OR salary<90000;
 select * from employee1 where name LIKE 'n%';
 select * from employee1 where name LIKE '%n';
 select * from employee1 where name LIKE 'n%n';
 select * from employee1 where name LIKE '%i%';
 update employee1 set DESIGNATION = "MD" where DESIGNATION = "FRESHER";
 update employee1 set salary = 100000 where salary = 60000;
 select * from employee1;